name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Composer install
      run: composer install

    - name: Run php-cs-fixer
      run: composer fix

    - name: Run phpstan
      run: composer phpstan
    
    - name: Create files
      run: touch tests/test_app/config/routes_compiled.php
    
    - name: Run phpunit
      run: vendor/bin/phpunit