name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Composer install
      run: composer install

    - name: Run php-cs-fixer
      env:
        PHP_CS_FIXER_IGNORE_ENV: true
      run: vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

    - name: Run phpstan
      run: vendor/bin/phpstan analyse -c phpstan.neon

    - name: Run phpunit
      run: vendor/bin/phpunit
